### ISSUE TITLE
Misleading error message if pyats is missing

### ISSUE THREAD

**Issue by nleiva** [clay584/parse_genie#10]
I didn't install `pyats` initially as the command didn't include it explicitly: Install Genie and pyATS. `pip install genie`. If you end up in that same state I was, you run into:

```python
>>> import genie
>>> from genie.conf.base import Device, Testbed
...
ModuleNotFoundError: No module named 'pyats'
```

The plugin however will report "_Genie package is not installed. To install, run 'pip install genie_", which is confusing as `genie` is installed.

```python
try:
    from genie.conf.base import Device, Testbed
    HAS_GENIE = True
except ImportError:
    HAS_GENIE = False
```

```python
    if not HAS_GENIE:
        raise AnsibleFilterError("parse_genie: Genie package is not installed. To install, run 'pip install genie'.")
```

**Comment by clay584** [comment]
This has been updated to be more clear. The pyATS team restructured the packaging and the installation method is slightly different than when this was originally written. Thanks for the feedback. It is fixed in version 1.5.1 and is now published on Ansible Galaxy.
