### ISSUE TITLE
{"msg": "parse_genie: local variable 'vrf_dict' referenced before assignment - Failed to parse command output."}

### ISSUE THREAD

**Issue by arynair** [clay584/parse_genie#11]
- name : LIST OF PROTOCOLS
    set_fact:
      my_protocols_isis: "{{ output['stdout'][0] | parse_genie(command='show isis ', os='iosxr') }}"
  - debug:
      var: my_protocols_isis

this task is giving the error on an IOS XR device
command line output:

TASK [LIST OF PROTOCOLS] ******************************************************************************
Wednesday 15 July 2020  06:11:07 +0000 (0:00:16.695)       0:00:16.982 ********
fatal: [xrdevice_1]: FAILED! => {"msg": "parse_genie: local variable 'vrf_dict' referenced before assignment - Failed to parse command output."}

Please help with fixing this issue

**Comment by clay584** [comment]
This appears to be a parser bug in the Cisco Genie library. I opened an issue on their project on your behalf.

https://github.com/CiscoTestAutomation/genieparser/issues/183

Cisco developers will need additional information from you to fix it.

**Comment by tahigash** [comment]
@arynair as @clay584 mentioned, this could be parser issue. could you please share the output on https://github.com/CiscoTestAutomation/genieparser/issues/183 or send to pyats-support-ext(at)cisco.com? We need the output of show command for investigation.

Let's continue on Issue on genieparser repo (https://github.com/CiscoTestAutomation/genieparser/issues/183) or email. thanks
