### ISSUE TITLE
Parser show ethernet service instance detail for IOS and IOS-XE not working - genie_parse: local variable ''micro_block_dict'' referenced before assignment

### ISSUE THREAD

**Issue by xcluysen** [clay584/parse_genie#2]
Simple Playbook used :
`# Test of PyATS / Genie

---
- name: pyATS testing
  hosts: Eos
  gather_facts: no
  connection: network_cli

  tasks:

  - name: Read in parse_genie role
    include_role:
      name: clay584.parse_genie
  - name: Run the show EFP command
    ios_command:
      commands:
        - show ethernet service instance detail
    register: showefp

  - name: Set EFP fact with Genie filter plugin
    set_fact:
      efp: "{{ showefp['stdout'][0] | parse_genie(command='show ethernet service instance detail', os='iosxe') }}"

  - name: Debug pyATS facts - EFPs to check data structure received
    debug:
     var: efp
`

Result from router command that can't be parsed (extract) :

    Service Instance ID: 149
    Service Instance Type: Static
    Description: Fiber Connexion to XXX-200-2182
    Associated Interface: TenGigabitEthernet0/1
    Associated EVC:
    L2protocol drop
    CE-Vlans:
    Encapsulation: dot1q 19 vlan protocol type 0x8100 second-dot1q 149 vlan protocol type 0x8100
    Rewrite: ingress tag pop 2 symmetric
    Interface Dot1q Tunnel Ethertype: 0x8100
    State: Up
    EFP Statistics:
       Pkts In   Bytes In   Pkts Out  Bytes Out
      36279507 3955205745   42299716 20480433984
    EFP Microblocks:
    ****************
    Microblock type: Bridge-domain
    Bridge-domain: 149

    Microblock type: L2Mcast
    L2 Multicast GID: 54

    Microblock type: dhcp_snoop
    L2 Multicast GID: 54

    Service Instance ID: 2001
    Service Instance Type: Static
    Description: Fiber Connexion (Layer 2) to XXX-200-2183
    Associated Interface: TenGigabitEthernet0/1
    Associated EVC:
    L2protocol drop
    CE-Vlans:
    Encapsulation: dot1q 21 vlan protocol type 0x8100 second-dot1q 2-148,150-4093 vlan protocol type 0x8100
    Rewrite: ingress tag pop 1 symmetric
    Interface Dot1q Tunnel Ethertype: 0x8100
    State: Up
    EFP Statistics:
       Pkts In   Bytes In   Pkts Out  Bytes Out
     356008885 51800659418  533687182 229082305074
    EFP Microblocks:
    ****************
    Microblock type: Bridge-domain
    Bridge-domain: 4149

    Microblock type: L2Mcast
    L2 Multicast GID: 54

    Microblock type: dhcp_snoop
    L2 Multicast GID: 54

**Comment by clay584** [comment]
Are you getting an ansible error? What is the output from the `efp` variable? Is it failing to parse a particular portion of that CLI output?

BTW, this is just the ansible filter plugin that calls Cisco's Genie library. If there is an issue with parsing the data successfully, you will need to file an issue on the [GenieParser](https://github.com/CiscoTestAutomation/genieparser) GitHub page.

**Comment by xcluysen** [comment]
The router output never get parsed. I get an Ansible/Python error about that variable being  referenced before being assigned at execution of genie_parse :
genie_parse: local variable ''micro_block_dict'' referenced before assignment
So the program aborts before the efp variable gets assigned.

**Comment by clay584** [comment]
Can you include the full ansible output so I can see the actual error?

**Comment by xcluysen** [comment]
Here it is.

I am not an ansible expert yet, if there is more debug available by turning a flag, tell me and I'll do it.

[root@ULYSSE-ANSIBLE Genie Tests Scripts]# ansible-playbook evc.yml

PLAY [pyATS testing] ************************************************************************************************************************************************************************************************************************

TASK [Read in parse_genie role] *************************************************************************************************************************************************************************************************************

TASK [Run the show EFP command] *************************************************************************************************************************************************************************************************************
ok: [Eos]

TASK [Set EFP fact with Genie filter plugin] ************************************************************************************************************************************************************************************************
fatal: [Eos]: FAILED! =>
  msg: 'genie_parse: local variable ''micro_block_dict'' referenced before assignment - Failed to parse command output.'

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
Eos                        : ok=1    changed=0    unreachable=0    failed=1

**Comment by jeaubin** [comment]
Hi, genie developer here - it seems an issue with one of our parser.  Can you send us your full device output; and we will look into it early next week! 

If you prefer for privacy reason, you can send your output at pyats-support-ext@cisco.com

**Comment by xcluysen** [comment]
Hi,

Please see attached sanitized version of the switch output (only Description field is changed).
[Acheloos-EFP.txt](https://github.com/clay584/parse_genie/files/3344937/Acheloos-EFP.txt)

Switch is a ME-3600X running IOS 15.4(3)S10.

Same problem/issue with command run on an ASR920-4SZ-A running IOS XE 3.18.4SP4
I also attach the sanitized version, as the output is a little bit different, being IOS XE.
[Ajax-EFP.txt](https://github.com/clay584/parse_genie/files/3344957/Ajax-EFP.txt)

**Comment by jeaubin** [comment]
Great,  thanks. We will look into it and let you know.

**Comment by jeaubin** [comment]
It has been fixed, and a beta package has been released

pip install genie.lis.parser --upgrade --pre

Give it a try and let us know.

Thanks

**Comment by xcluysen** [comment]
Hi JB,

Thanks for the update, however I get an error when trying to upgrade :

[root@ANSIBLE Genie Tests Scripts]# pip install genie.lis.parser --upgrade --pre
Collecting genie.lis.parser
  ERROR: Could not find a version that satisfies the requirement genie.lis.parser (from versions: none)
ERROR: No matching distribution found for genie.lis.parser

Am I missing something ?

Best Regards,
         Xavier.

**Comment by jeaubin** [comment]
@xcluysen - I sent it too quickly, This enhancement will be done today/tomorrow.

And ; pip install genie.libs.parser --upgrade --pre

Thanks,

**Comment by xcluysen** [comment]
Hi JB,

I have installed the latest parser (19.6.1b1), but the playbook gives exactly the same error as before :

TASK [Set EFP fact with Genie filter plugin] ***************************************************************************************
fatal: [Eos]: FAILED! =>
  msg: 'genie_parse: local variable ''micro_block_dict'' referenced before assignment - Failed to parse command output.'

**Comment by jeaubin** [comment]
Hi @xcluysen  - It has now been released,  the fix should work.

pip install genie.libs.parser --upgrade --pre

Let me know if all is good now

Thanks,

**Comment by clay584** [comment]
@xcluysen Is this working now? Can I close this issue?

**Comment by xcluysen** [comment]
@clay584 Yes it works, I sent email but apparently it failed to show here. You can close the issue.
