### ISSUE TITLE
404 Not Found for available parsers

### ISSUE THREAD

**Issue by abhi1805** [clay584/parse_genie#6]
I am not able to access https://pubhub.devnetcloud.com/media/pyats-packages/docs/genie/genie_libs/#/parsers which is giving error 404 as follows:

404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: media/pyats-packages/docs/genie/genie_libs/index.html
    RequestId: FBD5A1FCDC1305C5
    HostId: 2tqzn+1mFl8B4KMSbumow3j3AzwP8Aqm0b/LLVgHVTEfxpKD8cof8au3CCm5N4ImhWdFPKX0ksI=

**Comment by jeaubin** [comment]
The link has been changed to here : https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers
